version: '3'

services:
  webserver:
    build: .docker.webserver/
    container_name: cpanelapi_www
    volumes:
      - ./www/:/var/www/html
      - ./.docker.webserver/apache2.conf:/etc/apache2/apache2.conf
    depends_on:
      - mysql
    ports:
      - "8080:80"